import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { authOn,supabase } from '../lib/supabase.js'
import { carregarJornada,todas } from '../lib/jornada.js'
import { jornadaDemo } from '../lib/jornadaDemo.js'
import { capacidadeMensal } from '../lib/operacao.js'
import { hojeSP } from '../lib/prazos.js'
export default function CapacidadeMontagem(){
 const [base,setBase]=useState(()=>authOn?null:jornadaDemo().dados),[ausencias,setAusencias]=useState([]),[mes,setMes]=useState(hojeSP().slice(0,7)),[form,setForm]=useState({montador:'',inicio:hojeSP(),fim:hojeSP(),motivo:''}),[cancelar,setCancelar]=useState({}),[erro,setErro]=useState(''),[busy,setBusy]=useState(false)
 async function carregar(){const [b,a]=await Promise.all([carregarJornada(),todas(()=>supabase.from('montador_indisponibilidades').select('*').order('id'))]);setBase(b);setAusencias(a)}
 useEffect(()=>{if(authOn)carregar().catch(e=>setErro(e.message))},[])
 const linhas=capacidadeMensal(base?.registros||[],base?.pessoas||[],ausencias,mes,base?.config?.feriados||[])
 const pode=authOn&&['gestor','logistica'].includes(base?.eu?.papel)
 const set=(k,v)=>setForm(f=>({...f,[k]:v}))
 async function salvar(id){setBusy(true);setErro('');try{const r=id?await supabase.rpc('montador_cancelar_indisponibilidade',{p_id:id,p_motivo:cancelar[id]}):await supabase.rpc('montador_indisponivel',{p_montador:form.montador,p_inicio:form.inicio,p_fim:form.fim,p_motivo:form.motivo});if(r.error)throw r.error;await carregar();if(!id)setForm(f=>({...f,motivo:''}))}catch(e){setErro(e.message)}finally{setBusy(false)}}
 return <><div className="card"><h3>Capacidade de montagem</h3><p>Glauci acompanha os dias reservados e indisponíveis por montador. A reserva ocupa a agenda, mas a escala só é liberada após a quitação conferida.</p><div className="tools"><label>Mês<input className="input" type="month" value={mes} onChange={e=>setMes(e.target.value||hojeSP().slice(0,7))}/></label><Link className="btn ghost" to="/agenda-operacional">Abrir agenda por dia</Link></div><p className="sub">Estimativa em dias úteis de Curitiba, considerando uma pessoa por montador cadastrado. Não considera horas extras, produtividade ou equipes compartilhadas. O período reservado é usado para ocupação; a estimativa de esforço deve ser preenchida em cada montagem.</p>{!authOn&&<p className="sub">Exemplo com montadores fictícios. Nenhuma reserva é alterada.</p>}</div>{erro&&<div className="login-err" role="alert">{erro}</div>}
 <div className="table-wrap" style={{margin:'16px 0'}}><table><thead><tr><th>Montador</th><th>Dias úteis</th><th>Reservados</th><th>Indisponíveis</th><th>Livres</th><th>Montagens</th><th>Sem esforço estimado</th></tr></thead><tbody>{linhas.map(p=><tr key={p.usuario_id}><td>{p.nome}</td><td>{p.uteis}</td><td>{p.ocupados}</td><td>{p.indisponiveis}</td><td>{p.livres}</td><td>{p.montagens}</td><td>{p.semEstimativa}</td></tr>)}{!linhas.length&&<tr><td colSpan="7">Cadastre os montadores e seus acessos para calcular a capacidade.</td></tr>}</tbody></table></div>
 <div className="card"><h3>Indisponibilidades</h3><p>Férias, afastamentos e outros compromissos impedem reservas conflitantes. O cancelamento preserva o motivo e o autor no histórico.</p>{ausencias.filter(a=>a.inicio.slice(0,7)<=mes&&a.fim.slice(0,7)>=mes).map(a=><div className="card" key={a.id}><b>{base?.pessoas.find(p=>p.usuario_id===a.montador_id)?.nome}</b><p>{a.inicio} a {a.fim} · {a.motivo}</p>{a.cancelado_em?<p>Cancelada: {a.cancelamento_motivo}</p>:pode&&<><input className="input" aria-label={'Motivo de cancelamento '+a.id} placeholder="Motivo para cancelar a indisponibilidade" value={cancelar[a.id]||''} onChange={e=>setCancelar(c=>({...c,[a.id]:e.target.value}))}/><button className="btn ghost" disabled={busy||!cancelar[a.id]?.trim()} onClick={()=>salvar(a.id)}>Cancelar indisponibilidade</button></>}</div>)}
 <fieldset disabled={busy||!pode} style={{border:0,padding:0}}><div className="grid cols-2"><label>Montador<select className="input" value={form.montador} onChange={e=>set('montador',e.target.value)}><option value="">Selecione</option>{base?.pessoas.filter(p=>p.papel==='montador').map(p=><option key={p.usuario_id} value={p.usuario_id}>{p.nome}</option>)}</select></label><label>Motivo<input className="input" value={form.motivo} onChange={e=>set('motivo',e.target.value)}/></label><label>Início<input className="input" type="date" value={form.inicio} onChange={e=>set('inicio',e.target.value)}/></label><label>Fim<input className="input" type="date" value={form.fim} min={form.inicio} onChange={e=>set('fim',e.target.value)}/></label></div><button className="btn" style={{marginTop:12}} disabled={!pode||busy||!form.montador||!form.motivo.trim()} onClick={()=>salvar()}>Registrar indisponibilidade</button></fieldset></div></>
}
