import { Link } from 'react-router-dom'
import {useState} from 'react'

const CART = [
 {nome:'Vendedor exemplo A',recebidos:40,convertidos:8,anteriores:3,transferidos:2,abertos:26,perdidos:4},
 {nome:'Vendedor exemplo B',recebidos:30,convertidos:9,anteriores:1,transferidos:1,abertos:18,perdidos:2},
]
const CARTEIRAS = {
 '2026-08':[
  {nome:'Vendedor exemplo A',recebidos:32,convertidos:6,anteriores:2,transferidos:1,abertos:21,perdidos:4},
  {nome:'Vendedor exemplo B',recebidos:25,convertidos:5,anteriores:2,transferidos:2,abertos:15,perdidos:3},
 ],
 '2026-09':CART,
}
const mesLabel=m=>/^\d{4}-\d{2}$/.test(m)?new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(Number(m.slice(0,4)),Number(m.slice(5,7))-1,15)):''
const taxa=(n,d)=>d?(n/d*100).toFixed(1).replace('.',',')+'%':'Sem base'
const CONTAS = [
 {id:'EX-AGO',fornecedor:'Serviço anterior · exemplo',vencimento:'15/09/2026',valor:'R$ 500,00',status:'Aguardando conciliação',detalhe:'Exemplo do mês anterior. Documento e pagamento aguardam conciliação; a pendência continua aberta ao consultar setembro.'},
 {id:'EX-01',fornecedor:'Aluguel · exemplo',vencimento:'05/10/2026',valor:'A confirmar',status:'Cobrança não recebida',detalhe:'A obrigação mensal existe, mas o boleto ainda não chegou. Leia tem uma pendência para solicitar o documento. Não há valor inventado nem pagamento registrado.'},
 {id:'EX-02',fornecedor:'Fábrica · exemplo',vencimento:'08/10/2026',valor:'R$ 8.000,00',status:'Possível duplicidade',detalhe:'Uma cobrança semelhante já está registrada. Conferir número do título, favorecido, parcela e documento. Um reenvio pode ser a mesma cobrança; duas parcelas podem ser legítimas.'},
 {id:'EX-03',fornecedor:'Frete · exemplo',vencimento:'10/10/2026',valor:'R$ 180,00',status:'Aguardando conciliação',detalhe:'Comprovante anexado e execução informada. Ainda é necessário cruzar a transação com o extrato; o arquivo sozinho não certifica o pagamento.'},
 {id:'EX-04',fornecedor:'Serviço · exemplo',vencimento:'12/10/2026',valor:'R$ 950,00',status:'Boleto para conferir',detalhe:'Proposta de entrada por e-mail: mostrar anexo e mensagem original, conferir campos extraídos e vincular ao pedido antes de gerar o título. Caixa de e-mail ainda não conectada.'},
]
const SECOES = {
 'Resumo':[['Cliente','Cliente demonstrativo · ficha única'],['Vendedor','Vendedor exemplo A'],['Obra','Apartamento exemplo · Curitiba/PR'],['Próxima ação','Confirmar informações da obra'],['Regra','Um cliente pode ter várias obras e contratos.']],
 'Cliente e obra':[['Cadastro','Nome, telefone, e-mail e documento para contratação'],['Endereços','Cadastro e obra separados'],['Recebimento','Contato autorizado, acesso e restrições do condomínio'],['Venda futura','Situação da obra e aviso do cliente de que está pronta']],
 'Atendimento':[['Helena','Qualificação e origem preservadas'],['Briefing','Ambientes, expectativa, prazo e investimento estimado'],['Comunicação','Conversa e observações vinculadas à oportunidade'],['Distribuição','Quem recebeu, quando recebeu e eventuais transferências']],
 'Propostas e contratos':[['Promob','XML original e versões posteriores'],['Negociação','15% automático antes do desconto; autorizações por versão'],['Fechamento','Contrato aceito e evidência de assinatura; marco a homologar'],['Documento público','Preço final e condições; composição interna restrita']],
 'Jornada':[['Correção','Medição: 5 dias corridos; conferência: 12 dias úteis'],['Liberação','Guias, aprovação, implantação e pagamento da fábrica'],['Montagem','Entrega, agenda, montador e quitação conferida'],['Qualidade','Termo, assistência em 30 dias úteis e fotos']],
 'Documentos':[['Vendas','Briefing, XML, imagens, proposta e contrato'],['Correção / liberação','Planta, medidas, revisões, guias e pedido da fábrica'],['Montagem / qualidade','Entrega, termo, fotos e peças da assistência'],['Financeiro','Boleto, nota, comprovante e conciliação — acesso restrito'],['Em todos os arquivos','Categoria, versão, autor, data e vínculo; vários anexos por etapa']],
 'Tarefas e lembretes':[['Vendedor','Enviar planta · prazo de 2 dias úteis'],['Conferente','Concluir guias · contagem desde a medição'],['Glauci','Confirmar recebimento e acompanhar assistência'],['Leia','Conferir entrada, fábrica, saldo e obrigações mensais'],['Escalonamento','Atraso permanece visível e chega à gestão; reconhecer aviso não encerra tarefa']],
 'Histórico':[['Distribuição','Autor, vendedor de origem/destino e motivo'],['Proposta','Versão aceita e aprovação utilizada'],['Documentos','Substituições preservam a versão anterior'],['Financeiro','Baixa, conferência, conciliação e eventual estorno'],['Prazos','Marco original preservado, com justificativas de alterações']],
}
const tile=(nome,valor,nota)=><div className="card kpi" key={nome}><div className="label">{nome}</div><div className="value">{valor}</div><p className="sub">{nota}</p></div>
export default function PlanejamentoIntegrado(){
 const [mesComercial,setMesComercial]=useState('2026-09'),[mesFinanceiro,setMesFinanceiro]=useState('2026-10')
 const [aba,setAba]=useState('Análise comercial'),[vendedor,setVendedor]=useState('Todos'),[ficha,setFicha]=useState('Resumo'),[filtro,setFiltro]=useState('Todos'),[conta,setConta]=useState(null),[carteira,setCarteira]=useState(null)
 const rows=(CARTEIRAS[mesComercial]||[]).filter(r=>vendedor==='Todos'||r.nome===vendedor)
 const recebidos=rows.reduce((s,r)=>s+r.recebidos,0),convertidos=rows.reduce((s,r)=>s+r.convertidos,0),fechados=rows.reduce((s,r)=>s+r.convertidos+r.anteriores,0)
 const contasMes=CONTAS.filter(r=>r.vencimento.slice(6)+'-'+r.vencimento.slice(3,5)===mesFinanceiro)
 const anteriores=CONTAS.filter(r=>r.vencimento.slice(6)+'-'+r.vencimento.slice(3,5)<mesFinanceiro)
 const lista=contasMes.filter(r=>filtro==='Todos'||r.status===filtro)
 const contar=status=>contasMes.filter(r=>r.status===status).length
 return <>
  <div className="card" style={{marginBottom:16}}><h3>Novos controles disponíveis na prévia</h3><div className="tools"><Link className="btn ghost" to="/pendencias">Pendências da equipe</Link><Link className="btn ghost" to="/jornada">Ficha e documentos</Link><Link className="btn ghost" to="/revisao-mensal">Revisão mensal</Link><Link className="btn ghost" to="/capacidade-montagem">Capacidade dos montadores</Link></div></div>
  <div className="card" style={{marginBottom:18,borderTop:'4px solid #ab8957'}}>
   <span className="pill">Proposta de organização · exemplos fictícios</span>
   <h3 style={{fontSize:28,marginTop:14}}>Uma ficha. Todos os setores. Números conferíveis.</h3>
   <p>Prévia para revisar o desenho da integração. Os controles apresentados aqui ainda não estão ativos no banco nem no e-mail.</p>
   <div className="tools" role="tablist" aria-label="Proposta integrada" style={{flexWrap:'wrap',marginTop:18}}>{['Análise comercial','Ficha do cliente','Central da Leia'].map(a=><button role="tab" aria-selected={aba===a} className={'btn '+(aba===a?'':'ghost')} key={a} onClick={()=>setAba(a)}>{a}</button>)}</div>
  </div>
  {aba==='Análise comercial'&&<>
   <div className="card" style={{marginBottom:16}}><div className="between" style={{gap:16,flexWrap:'wrap'}}><div><h3>Leads recebidos × conversão</h3><p className="sub">Exemplo de {mesLabel(mesComercial)} · corte no fim do mês selecionado · distribuição e fechamento têm datas próprias.</p></div><label>Mês e ano<input aria-label="Mês da análise comercial" type="month" className="input" value={mesComercial} onChange={e=>{if(e.target.value){setMesComercial(e.target.value);setCarteira(null)}}}/></label><label>Vendedor<select aria-label="Vendedor da análise" className="input" value={vendedor} onChange={e=>{setVendedor(e.target.value);setCarteira(null)}}><option>Todos</option>{CART.map(r=><option key={r.nome}>{r.nome}</option>)}</select></label></div></div>
   <div className="grid cols-3" style={{marginBottom:18}}>{tile('Leads novos distribuídos',rows.length?recebidos:'—','Recebidos na carteira no mês do exemplo')}{tile('Conversão dessa carteira',taxa(convertidos,recebidos),`${convertidos} de ${recebidos} leads; sem misturar meses`)}{tile('Fechamentos no mês',rows.length?fechados:'—','Inclui clientes recebidos em meses anteriores')}</div>
   <div className="table-wrap"><table><thead><tr><th>Vendedor</th><th>Recebidos</th><th>Convertidos da carteira</th><th>Conversão</th><th>Fechamentos no mês</th><th></th></tr></thead><tbody>{!rows.length&&<tr><td colSpan="6" className="empty">Sem dados demonstrativos para este mês. Isso não significa zero vendas.</td></tr>}{rows.map(r=><tr key={r.nome}><td>{r.nome}</td><td>{r.recebidos}</td><td>{r.convertidos}</td><td><span className="badge ok">{(r.convertidos/r.recebidos*100).toFixed(1).replace('.',',')}%</span></td><td>{r.convertidos+r.anteriores} <span className="sub">({r.anteriores} de meses anteriores)</span></td><td><button className="btn ghost sm" onClick={()=>setCarteira(r)}>Entender a conta</button></td></tr>)}</tbody></table></div>
   {carteira&&<div className="card" style={{marginTop:16}}><h3>{carteira.nome} · composição do exemplo</h3><p>{carteira.recebidos} recebidos = {carteira.convertidos} convertidos + {carteira.abertos} em atendimento + {carteira.perdidos} perdidos + {carteira.transferidos} transferidos ainda sem fechamento.</p><p>Os {carteira.anteriores} fechamentos de clientes recebidos antes de {mesLabel(mesComercial)} entram no total de vendas do mês, sem aumentar a conversão da carteira de {mesLabel(mesComercial)}.</p><p className="sub">Na versão operacional, cada número abrirá os leads e eventos que o compõem. Transferências terão origem, destino e autor preservados.</p></div>}
   <div className="card" style={{marginTop:16}}><h3>Comparação mês a mês</h3><p className="sub">Mesmo filtro de vendedor · cada carteira medida até o fim de seu mês · exemplos disponíveis em agosto e setembro de 2026.</p><div className="table-wrap"><table><thead><tr><th>Mês</th><th>Leads recebidos</th><th>Convertidos dessa carteira</th><th>Conversão</th><th>Fechamentos no mês</th></tr></thead><tbody>{Object.entries(CARTEIRAS).map(([mes,base])=>{const rs=base.filter(r=>vendedor==='Todos'||r.nome===vendedor),rec=rs.reduce((s,r)=>s+r.recebidos,0),conv=rs.reduce((s,r)=>s+r.convertidos,0);return <tr key={mes}><td><button className="btn ghost sm" onClick={()=>{setMesComercial(mes);setCarteira(null)}}>{mesLabel(mes)}</button></td><td>{rec}</td><td>{conv}</td><td>{taxa(conv,rec)}</td><td>{rs.reduce((s,r)=>s+r.convertidos+r.anteriores,0)}</td></tr>})}</tbody></table></div></div>
   <div className="card" style={{marginTop:16}}><h3>O que acompanhar junto</h3><p>Origem dos leads · primeiro atendimento · apresentações · propostas · motivos de perda · transferências · clientes sem próxima ação · venda normal/futura.</p><p className="sub">Quantidade de contratos, dinheiro recebido e gratificação são medidas separadas. O valor estimado do briefing não será tratado como venda confirmada.</p></div>
  </>}
  {aba==='Ficha do cliente'&&<div className="card"><h3>Cliente demonstrativo</h3><p className="sub">Cadastro progressivo: os dados exigidos acompanham a etapa do atendimento.</p><div className="tools" style={{flexWrap:'wrap',margin:'18px 0'}}>{Object.keys(SECOES).map(a=><button key={a} className={'btn sm '+(ficha===a?'':'ghost')} onClick={()=>setFicha(a)}>{a}</button>)}</div><h3>{ficha}</h3><div className="table-wrap"><table><tbody>{SECOES[ficha].map(([k,v])=><tr key={k}><th style={{width:'28%'}}>{k}</th><td>{v}</td></tr>)}</tbody></table></div><p className="sub" style={{marginTop:14}}>Exemplo de estrutura, sem documentos pessoais. Arquivos e valores serão visíveis somente aos perfis autorizados.</p></div>}
  {aba==='Central da Leia'&&<>
   <div className="card" style={{marginBottom:16}}><h3>Dois e-mails, uma conferência</h3><p>Os boletos das duas caixas serão reunidos aqui, com indicação da origem e acesso à mensagem original. A mesma cobrança recebida nas duas caixas deverá aparecer uma única vez, com ambas as mensagens vinculadas.</p><p className="sub">Integração planejada: aguardando identificação dos dois e-mails e seus provedores. Nenhuma caixa está conectada nesta prévia.</p></div>
   <div className="card" style={{marginBottom:16}}><label>Mês e ano<input aria-label="Mês do financeiro" className="input" type="month" value={mesFinanceiro} onChange={e=>{if(e.target.value){setMesFinanceiro(e.target.value);setConta(null)}}}/></label><p className="sub">Período: {mesLabel(mesFinanceiro)} · cobranças pelo vencimento. Exemplos disponíveis em setembro e outubro de 2026.</p><p className="sub">Na integração real, caixa será separado pela data efetiva do pagamento e DRE pela competência definida. Pendências anteriores continuam abertas mesmo ao trocar de mês.</p></div>
   <div className="grid cols-3" style={{marginBottom:18}}>{tile('Cobrança esperada' ,contar('Cobrança não recebida'),'Documento ainda não recebido')}{tile('Revisar possível duplicidade',contar('Possível duplicidade'),'Sem excluir nem estornar automaticamente')}{tile('Conciliar com extrato',contar('Aguardando conciliação'),'Comprovante anexado não basta')}</div>
   <div className="card" style={{marginBottom:16}}><h3>Fechamento mensal sem pendências escondidas</h3><p>Obrigação prevista → cobrança → conferência → pagamento → conciliação.</p><p className="sub">Exemplo de {mesLabel(mesFinanceiro)}. Boletos por e-mail entram em conferência. Não há conexão de e-mail ou execução bancária nesta prévia.</p><label>Filtrar pendência<select className="input" aria-label="Filtrar pendência financeira" value={filtro} onChange={e=>{setFiltro(e.target.value);setConta(null)}}><option>Todos</option>{[...new Set(CONTAS.map(r=>r.status))].map(status=><option key={status}>{status}</option>)}</select></label></div>
   <div className="table-wrap"><table><thead><tr><th>Referência</th><th>Obrigação</th><th>Vencimento</th><th>Valor</th><th>Conferência</th><th></th></tr></thead><tbody>{!lista.length&&<tr><td colSpan="6" className="empty">Sem exemplos para este mês e filtro; não é uma confirmação de que todas as contas estão pagas.</td></tr>}{lista.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.fornecedor}</td><td>{r.vencimento}</td><td>{r.valor}</td><td><span className="badge warn">{r.status}</span></td><td><button className="btn ghost sm" onClick={()=>setConta(r)}>Ver controle proposto</button></td></tr>)}</tbody></table></div>
   {anteriores.length>0&&<div className="card" style={{marginTop:16,borderColor:'var(--warn)'}}><h3>Pendências de meses anteriores · {anteriores.length}</h3><p className="sub">Separadas dos indicadores do mês selecionado. Trocar de mês não encerra nem oculta estas pendências.</p>{anteriores.map(r=><p key={r.id}><b>{r.id} · {r.fornecedor}</b> · {r.vencimento} · {r.status} <button className="btn ghost sm" onClick={()=>setConta(r)}>Ver controle proposto</button></p>)}</div>}
   {conta&&<div role="status" className="card" style={{marginTop:16}}><h3>{conta.id} · {conta.status}</h3><p>{conta.detalhe}</p></div>}
   <div className="card" style={{marginTop:16}}><h3>Comprovantes com contexto</h3><p>Favorecido · título/parcela · contrato ou despesa · valor real · data real · conta · transação · quem registrou · quem conferiu · documento original.</p><p className="sub">A mesma transação não pode gerar duas baixas. Pagamentos parciais e em lote terão alocação explícita. Um Pix feito fora do sistema só pode ser identificado quando seu registro ou extrato for disponibilizado.</p></div>
  </>}
 </>
}
