import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { authOn,supabase } from '../lib/supabase.js'
import { carregarJornada } from '../lib/jornada.js'
import { hojeSP } from '../lib/prazos.js'
const CHECKS={obrigacoes:'Contas recorrentes e boletos esperados conferidos, incluindo os dois e-mails',documentos:'Documentos e comprovantes vinculados aos lançamentos',pagamentos:'Pagamentos comparados com as saídas do extrato',recebimentos:'Recebimentos comparados com as entradas do extrato',conciliacao:'Diferenças de valores, taxas e datas esclarecidas',duplicidades:'Possíveis duplicidades analisadas',rateios:'Despesas por contrato e competência revisadas'}
export default function RevisaoMensal(){
 const [mes,setMes]=useState(hojeSP().slice(0,7)),[r,setR]=useState(null),[check,setCheck]=useState({}),[obs,setObs]=useState(''),[motivo,setMotivo]=useState(''),[eventos,setEventos]=useState([]),[eu,setEu]=useState(null),[erro,setErro]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(authOn)
 useEffect(()=>{if(authOn)carregarJornada().then(b=>setEu(b.eu)).catch(e=>setErro(e.message))},[])
 useEffect(()=>{let vivo=true;setR(null);setCheck({});setObs('');setEventos([]);setMotivo('');setErro('');if(!authOn)return
  setLoading(true);Promise.all([supabase.from('revisoes_mensais').select('*').eq('mes',mes+'-01').maybeSingle(),supabase.from('revisoes_mensais_eventos').select('*').eq('mes',mes+'-01').order('id',{ascending:false})]).then(([a,b])=>{if(a.error)throw a.error;if(b.error)throw b.error;if(vivo){setR(a.data);setCheck(a.data?.checklist||{});setObs(a.data?.observacoes||'');setEventos(b.data)}}).catch(e=>{if(vivo)setErro(e.message)}).finally(()=>{if(vivo)setLoading(false)});return()=>{vivo=false}
 },[mes])
 const permitido=authOn&&['gestor','financeiro'].includes(eu?.papel)&&!loading&&!erro
 const fechado=r?.status==='Conferido',completo=Object.keys(CHECKS).every(k=>check[k]),encerrado=mes<hojeSP().slice(0,7)
 async function salvar(conferir=false,reabrir=false){setBusy(true);setErro('');try{
  const x=await supabase.rpc('revisao_mensal_salvar',{p_mes:mes+'-01',p_checklist:check,p_observacoes:obs,p_versao:r?.versao||0,p_conferir:conferir,p_reabrir:reabrir,p_motivo:motivo});if(x.error)throw x.error;setR(x.data);setMotivo('')
  const h=await supabase.from('revisoes_mensais_eventos').select('*').eq('mes',mes+'-01').order('id',{ascending:false});if(h.error)throw h.error;setEventos(h.data)
 }catch(e){setErro(e.message)}finally{setBusy(false)}}
 return <><div className="card"><h3>Revisão mensal do financeiro</h3><p>Leia confere o período; a gestão pode reabrir um mês conferido, sempre registrando o motivo.</p><label>Mês da revisão<input className="input" style={{maxWidth:220}} type="month" max={hojeSP().slice(0,7)} value={mes} disabled={busy} onChange={e=>setMes(e.target.value||hojeSP().slice(0,7))}/></label><p><span className="pill">{loading?'Carregando…':r?.status||'Revisão não iniciada'}</span></p>{!authOn&&<p className="sub">Prévia local: experimente o checklist. A conferência não é gravada e nenhum mês real é bloqueado.</p>}
 <p className="sub">A conferência é manual. Marcar estes itens não consulta o banco nem os e-mails e não detecta automaticamente boletos ausentes. A integração com os dois e-mails e a conciliação bancária ainda precisam ser ativadas.</p></div>
 {erro&&<div className="login-err" role="alert">{erro} <button className="btn ghost" onClick={()=>window.location.reload()}>Recarregar revisão</button></div>}
 <div className="grid cols-2" style={{marginTop:16}}><div className="card"><h3>Conferências do mês</h3>{Object.entries(CHECKS).map(([k,t])=><label key={k} style={{display:'flex',gap:12,margin:'18px 0'}}><input type="checkbox" checked={!!check[k]} disabled={fechado||busy||loading||(authOn&&!permitido)} onChange={e=>setCheck(c=>({...c,[k]:e.target.checked}))}/><span>{t}</span></label>)}<label>Observações da revisão<textarea className="input" value={obs} disabled={fechado||busy||loading||(authOn&&!permitido)} onChange={e=>setObs(e.target.value)}/></label>
 {!fechado?<div className="tools" style={{marginTop:16,flexWrap:'wrap'}}><button className="btn ghost" disabled={!permitido||busy} onClick={()=>salvar()}>Salvar andamento</button><button className="btn" disabled={!permitido||busy||!completo||!encerrado} onClick={()=>salvar(true)}>Concluir conferência</button>{!encerrado&&<p className="sub">A conclusão fica disponível depois do último dia do mês.</p>}</div>:<><p>Mês conferido. Os lançamentos protegidos exigem reabertura antes de qualquer alteração.</p>{eu?.papel==='gestor'&&<><label>Justificativa para reabertura<textarea className="input" value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><button className="btn" disabled={busy||!motivo.trim()} onClick={()=>salvar(false,true)}>Reabrir mês</button></>}</>}
 </div><div className="card"><h3>Fontes para conferir</h3><p><Link to="/pagamentos">Pagamentos e comprovantes</Link></p><p><Link to="/recebiveis">Recebimentos</Link></p><p><Link to="/contas-fixas">Contas recorrentes</Link></p><p><Link to="/dre">DRE e competência</Link></p><h3>Histórico da revisão</h3>{!eventos.length&&<p>Sem ações registradas para este mês.</p>}{eventos.map(h=><p key={h.id}>{new Date(h.criado_em).toLocaleString('pt-BR')} · {h.motivo}<br/><span className="sub">Responsável: {h.autor} · versão {h.atual.versao}</span></p>)}<p className="sub">Proteção preparada para pagamentos, recebimentos, custos, vendas e assistências das fontes existentes. Não equivale a fechamento contábil. Gratificações e novas fontes precisam ser incorporadas após homologação de suas regras.</p></div></div></>
}
