import { useEffect, useState } from 'react'
import { authOn, supabase } from '../lib/supabase.js'
import { listarItens, salvarItem, uploadColaboracao, abrirAnexo } from '../lib/colaboracao.js'
import { todas } from '../lib/jornada.js'
import { PAPEIS, MARCOS } from '../lib/operacao.js'
import { hojeSP } from '../lib/prazos.js'

const TIPOS={documento:'Documentos',tarefa:'Tarefas e devoluções',observacao:'Observações',excecao:'Exceções',historico:'Histórico dos complementos'}
const SETORES={vendas:'Vendas',correcao:'Correção',liberacao:'Liberação',montagem:'Montagem',qualidade:'Qualidade',financeiro:'Financeiro reservado'}
const EXCECOES=['Pagamento parcial','Entrega parcial','Várias fábricas','Troca de vendedor','Cancelamento','Assistência reaberta','Outro']
export default function RegistroComplementos({registro,registros=[],pessoas=[],eu,setor='vendas'}){
 const [aba,setAba]=useState('tarefa'),[itens,setItens]=useState([]),[eventos,setEventos]=useState([]),[erro,setErro]=useState(''),[busy,setBusy]=useState(false)
 const inicial=()=>({setor:eu?.papel==='financeiro'?'financeiro':eu?.papel==='correcao'?'correcao':eu?.papel==='logistica'?'montagem':setor,titulo:'',descricao:'',prazo:hojeSP(),responsavel_papel:'vendedor',responsavel_id:'',bloqueia:'',categoria:'Outro',grupo:'',ambiente:''})
 const [form,setForm]=useState(inicial),[file,setFile]=useState(null),[conclusoes,setConclusoes]=useState({})
 const pode=authOn&&registro.id&&eu&&eu.papel!=='montador'
 const set=(k,v)=>setForm(f=>({...f,[k]:v}))
 async function carregar(){const ids=registros.filter(r=>r.contrato_id===registro.contrato_id).map(r=>r.id);const xs=await listarItens(ids.length?ids:registro.id);setItens(xs);setEventos(xs.length?await todas(()=>supabase.from('jornada_itens_eventos').select('*').in('item_id',xs.map(x=>x.id)).order('id',{ascending:false})):[])}
 useEffect(()=>{if(authOn&&registro.id)carregar().catch(e=>setErro(e.message))},[registro.id])
 async function gravar(){setBusy(true);setErro('');try{let d={...form};if(aba==='documento'){d.arquivo=await uploadColaboracao(file);d.nome=file.name}await salvarItem(form.registro_id||registro.id,aba,d);setForm(inicial());setFile(null);await carregar()}catch(e){setErro(e.message)}finally{setBusy(false)}}
 async function concluir(i){setBusy(true);setErro('');try{await salvarItem(i.registro_id,'tarefa',{...i.dados,setor:i.setor,titulo:i.titulo,concluida:true,conclusao:conclusoes[i.id]},i);await carregar()}catch(e){setErro(e.message)}finally{setBusy(false)}}
 async function decidir(i,status){setBusy(true);setErro('');try{const r=await supabase.rpc('colaboracao_excecao_decidir',{p_id:i.id,p_status:status,p_motivo:conclusoes[i.id],p_versao:i.versao});if(r.error)throw r.error;await carregar()}catch(e){setErro(e.message)}finally{setBusy(false)}}
 const visiveis=itens.filter(i=>i.tipo===aba).sort((a,b)=>b.criado_em.localeCompare(a.criado_em))
 const setores=Object.entries(SETORES).filter(([k])=>!authOn||eu?.papel==='gestor'||eu?.papel==='financeiro'||(eu?.papel==='vendedor'&&k==='vendas')||(eu?.papel==='correcao'&&['correcao','liberacao'].includes(k))||(eu?.papel==='logistica'&&['liberacao','montagem','qualidade'].includes(k)))
 return <section className="card" style={{marginTop:18}}><h3>Informações do atendimento</h3><p>Arquivos, lembretes e decisões de todos os atendimentos deste contrato, conforme seu acesso. Novos itens ficam vinculados ao atendimento aberto.</p>
 <div className="tools" style={{flexWrap:'wrap',gap:8}}>{Object.entries(TIPOS).map(([k,v])=><button key={k} className={'btn '+(aba===k?'':'ghost')} onClick={()=>{setAba(k);setForm(inicial());setFile(null)}}>{v}</button>)}</div>
 {!authOn&&<p className="sub">Prévia: os campos abaixo mostram como será o cadastro. Anexos e gravações estarão disponíveis após ativar os acessos.</p>}
 {!registro.id&&<p>Salve o registro principal antes de acrescentar informações.</p>}
 {erro&&<div role="alert" className="login-err">{erro}</div>}
 {aba==='historico'?<>{eventos.length===0&&<p>Nenhuma alteração registrada nos complementos.</p>}{eventos.map(e=><p key={e.id}>{new Date(e.criado_em).toLocaleString('pt-BR')} · {pessoas.find(p=>p.usuario_id===e.autor)?.nome||e.autor} · {e.atual.titulo} · versão {e.atual.versao}{e.atual.dados?.conclusao&&` · ${e.atual.dados.conclusao}`}{e.atual.dados?.decisao&&` · ${e.atual.dados.status}: ${e.atual.dados.decisao}`}</p>)}</>:<>
 {aba==='excecao'&&<p className="sub">Registre a ocorrência e crie uma tarefa para o responsável. Este registro não altera valores, prazos ou liberações; pagamentos parciais, cancelamentos e desdobramentos por fábrica ainda exigem tratamento específico.</p>}
 {visiveis.length===0&&<p>Nenhum item registrado nesta aba.</p>}
 {visiveis.map(i=><article className="card" key={i.id} style={{margin:'12px 0'}}><b>{i.titulo}</b><p className="sub">{SETORES[i.setor]} · {pessoas.find(p=>p.usuario_id===i.criado_por)?.nome||'Responsável registrado'} · {new Date(i.criado_em).toLocaleString('pt-BR')}</p><p style={{whiteSpace:'pre-wrap'}}>{i.dados.descricao}</p>
 {aba==='documento'&&<><p>Versão {i.dados.revisao} · {i.dados.categoria} · {i.dados.ambiente||'Todos os ambientes'}</p><button className="btn ghost" onClick={()=>abrirAnexo(i.dados.arquivo).catch(e=>setErro(e.message))}>Abrir {i.dados.nome}</button><button className="btn ghost" disabled={!pode||busy} onClick={()=>setForm({...inicial(),registro_id:i.registro_id,setor:i.setor,titulo:i.titulo,grupo:i.dados.grupo,categoria:i.dados.categoria,ambiente:i.dados.ambiente})}>Adicionar nova versão</button></>}
 {aba==='excecao'&&<><span className="pill">{i.dados.categoria} · {i.dados.status}</span>{i.dados.decisao&&<p>{i.dados.decidido_por}: {i.dados.decisao}</p>}{pode&&eu?.aprovadora&&['Em análise','Em tratamento'].includes(i.dados.status)&&<><label>Decisão e providências<textarea className="input" value={conclusoes[i.id]||''} onChange={e=>setConclusoes(c=>({...c,[i.id]:e.target.value}))}/></label>{(i.dados.status==='Em análise'?['Em tratamento','Rejeitada']:['Resolvida']).map(status=><button key={status} className="btn ghost" disabled={busy||!conclusoes[i.id]?.trim()} onClick={()=>decidir(i,status)}>{status==='Em tratamento'?'Encaminhar para tratamento':status==='Rejeitada'?'Rejeitar solicitação':'Registrar resolução'}</button>)}</>}</>}
 {aba==='tarefa'&&<><p>{PAPEIS[i.dados.responsavel_papel]}{i.dados.responsavel_id&&` · ${pessoas.find(p=>p.usuario_id===i.dados.responsavel_id)?.nome||'Pessoa atribuída'}`} · prazo {i.dados.prazo} · {i.dados.concluida?'Concluída':'Em aberto'}</p>{i.dados.bloqueia&&<p>Bloqueia: {MARCOS[i.dados.bloqueia]}</p>}{i.dados.concluida?<p>Conclusão: {i.dados.conclusao}</p>:pode&&(eu.papel==='gestor'||(eu.papel===i.dados.responsavel_papel&&(!i.dados.responsavel_id||i.dados.responsavel_id===eu.usuario_id)))&&<><textarea className="input" aria-label={'Resolução: '+i.titulo} placeholder="Como a pendência foi resolvida" value={conclusoes[i.id]||''} onChange={e=>setConclusoes(c=>({...c,[i.id]:e.target.value}))}/><button className="btn" disabled={busy||!conclusoes[i.id]?.trim()} onClick={()=>concluir(i)}>Concluir tarefa</button></>}</>}
 </article>)}
 <fieldset disabled={busy||(!pode&&authOn)} style={{border:0,padding:0,marginTop:20}}><h4>{form.grupo?'Nova versão do documento':'Adicionar informação'}</h4><div className="grid cols-2">
 <label>Setor<select className="input" value={form.setor} disabled={!!form.grupo} onChange={e=>set('setor',e.target.value)}>{setores.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Título<input className="input" value={form.titulo} onChange={e=>set('titulo',e.target.value)}/></label></div>
 <label>{aba==='excecao'?'Justificativa / providências necessárias':'Descrição / motivo da devolução'}<textarea className="input" value={form.descricao} onChange={e=>set('descricao',e.target.value)}/></label>
 {aba==='tarefa'&&<div className="grid cols-2"><label>Prazo original<input className="input" type="date" value={form.prazo} onChange={e=>set('prazo',e.target.value)}/></label><label>Responsável pelo atendimento<select className="input" value={form.responsavel_papel} onChange={e=>setForm(f=>({...f,responsavel_papel:e.target.value,responsavel_id:''}))}>{Object.entries(PAPEIS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Pessoa<select className="input" value={form.responsavel_id} onChange={e=>set('responsavel_id',e.target.value)}><option value="">Equipe responsável</option>{pessoas.filter(p=>p.papel===form.responsavel_papel).map(p=><option key={p.usuario_id} value={p.usuario_id}>{p.nome}</option>)}</select></label><label>Etapa que depende desta tarefa<select className="input" value={form.bloqueia} onChange={e=>set('bloqueia',e.target.value)}>{Object.entries(MARCOS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>}
 {aba==='documento'&&<><div className="grid cols-2"><label>Categoria<input className="input" value={form.categoria} onChange={e=>set('categoria',e.target.value)}/></label><label>Ambiente<input className="input" value={form.ambiente} onChange={e=>set('ambiente',e.target.value)}/></label></div><label>Arquivo privado · até 50 MB<input key={form.grupo+itens.length} type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></>}
 {aba==='excecao'&&<label>Situação<select aria-label="Situação" className="input" value={form.categoria} onChange={e=>set('categoria',e.target.value)}>{EXCECOES.map(v=><option key={v}>{v}</option>)}</select></label>}
 <button className="btn" style={{marginTop:12}} disabled={!pode||busy||!form.titulo.trim()||(aba==='documento'&&!file)} onClick={gravar}>{busy?'Registrando…':authOn?'Registrar no histórico':'Gravação disponível após ativação'}</button></fieldset>
 </>}
 </section>
}
